name: CI

on: [ 'push', 'pull_request' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: Formats P${{ matrix.php }} | ${{ matrix.os }} | ${{ matrix.dependency-version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # TODO: Pretty sure I don't need these... but I need a PHP grey beard to tell me otherwise
          # extensions: dom, mbstring, zip
          # tools: prestissimo
          # coverage: pcov

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Coding Style Checks
        run: composer check

      - name: Refactor Checks
        run: composer run rector:dry-run

      - name: Type Checks
        run: composer test:types

      - name: Type Coverage
        run: composer test:type-coverage min=100

